/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Aymeric
 */
public class TP2Ex2Panel extends javax.swing.JPanel {
    
    Color DEFAULTCOLOR = Color.blue;
    
    int WIDTH_FINE = 5;
    int WIDTH_WIDE = 10;
    
    protected List<ColorPoint> pointList = new ArrayList<>();
    protected Color selectedColor = DEFAULTCOLOR;
    protected int selectedWidth = WIDTH_FINE;
    
    
    
    /**
     * Creates new form TP2Ex2Panel
     */
    public TP2Ex2Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D)g;
            
            for (ColorPoint p : pointList) {
                g2d.setColor(p.getColor());
                g2d.fillOval(p.getX(), p.getY(), p.getSize(), p.getSize());
                //System.out.println(p.toString());
            }
        }
    
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        int x = evt.getX();
        int y = evt.getY();
        
        //System.out.println(x + "," + y);
        
        ColorPoint newPoint = new ColorPoint(selectedWidth, selectedColor, x, y);
        pointList.add(newPoint);
        //System.out.println("new point:" + newPoint.toString());
        repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        int x = evt.getX();
        int y = evt.getY();
        
        //System.out.println(x + "," + y);
        
        ColorPoint newPoint = new ColorPoint(selectedWidth, selectedColor, x, y);
        pointList.add(newPoint);
        //System.out.println("new point:" + newPoint.toString());
        repaint();
    }//GEN-LAST:event_formMouseDragged
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
